#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Windows (on /dev/sda1)" {
    insmod ntfs
    set root='(hd0,msdos1)'
    chainloader +1
}

menuentry "Puppy fossapup64 9.6 (on /dev/sda4)" {
    set root='(hd0,msdos4)'
    linux /vmlinuz pmedia=atahd pfix=fsck
    initrd /initrd.gz
}

menuentry "Puppy fossapup64 9.6 (on /dev/sda2/FRUGAL_FOSSAPUP)" {
    set root='(hd0,msdos2)'
    linux /FRUGAL_FOSSAPUP/vmlinuz psubdir=/FRUGAL_FOSSAPUP pmedia=atahd pfix=fsck
    initrd /FRUGAL_FOSSAPUP/initrd.gz
}

menuentry "Puppy bionicpup64 8.0 (on /dev/sda4/bionicpup648.0frugal)" {
    set root='(hd0,msdos4)'
    linux /bionicpup648.0frugal/vmlinuz psubdir=/bionicpup648.0frugal pmedia=atahd pfix=fsck
    initrd /bionicpup648.0frugal/initrd.gz
}
